ticker: TQQQ

signal:
  type: daily
  drop_threshold: -0.07
  rise_threshold: 0.08

trade:
  buy_amount_usd: 500
  sell_amount_usd: 500

notifications:
  pushover:
    enabled: true
    recipients:
      - wendi
      - husband

  email:
    enabled: true
    to:
      - wendizeng11@gmail.com
      - pengfukang@gmail.com

quiet_hours:
  market_only: true
